---
collections:
  - name: community.crypto

  - name: ansible.posix
    version: 1.2.0

#  - name: /tmp/community-dns-1.2.0.tar.gz

#  - name: http://www.example.com/redhat-insights-1.0.5.tar.gz

  - name: git+https://github.com/ansible-collections/community.general.git
    version: main

  - name: redhat.rhel_system_roles
