- name: SE test
  hosts: all
  roles:
    - role: zabbix_agent
      # remove_previous_packages: true
      package_state: latest
      agent_variant: 2
      param_listenport: 10050
      agent_major_version: 6.0
      # source_scripts_dir: scripts
      # param_userparameter:
      #   - traces, /var/lib/zabbix/ZABBIX_AGENT2/scripts/traces.sh
      #   - suls, sudo ls /root
      apply_seport: true
      apply_semodule: true
      seboolean_zabbix_run_sudo: "on"
