---
### Verify playbook does not inherit role defaults and vars. To make it happen import the role tasks.
- name: Verify
  hosts: all
  tasks:

    - name: Import defaults, vars and verification tasks from zabbix_agent role
      ansible.builtin.include_role:
        name: zabbix_agent
        tasks_from: verify
        # public: true
      vars:
        zabbix_agent_verification: true
