---
- name: Import common definitions
  import_role:
    name: openafs_contrib.openafs.openafs_common

- name: Gather operating specific specific variables
  include_vars: "{{ afs_server_os_item }}"
  loop_control:
    loop_var: afs_server_os_item
  with_first_found:
    - "{{ role_path }}/vars/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_distribution | replace(' ', '_') }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_os_family }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_system }}.yaml"
    - "{{ role_path }}/vars/defaults.yaml"

- import_tasks: "pre-install/check-variables.yaml"
- import_tasks: "pre-install/server-etc-hosts.yaml"
- import_tasks: "pre-install/server-partitions.yaml"
- include_tasks: "pre-install/firewall-{{ afs_firewall | default('none') }}.yaml"
- include_tasks: "pre-install/security-policies-{{ afs_security_model }}.yaml"

- name: Install server
  include_tasks: "{{ afs_server_install_item }}"
  loop_control:
    loop_var: afs_server_install_item
  with_first_found:
    - "{{ role_path }}/tasks/install/{{ afs_install_method }}-{{ ansible_os_family | lower }}.yaml"
    - "{{ role_path }}/tasks/install/{{ afs_install_method }}.yaml"
    - "{{ role_path }}/tasks/install/unknown.yaml"

- import_tasks: "post-install/server-config.yaml"
- import_tasks: "post-install/server-key.yaml"
- include_tasks: "post-install/security-contexts-{{ afs_security_model }}.yaml"
- include_tasks: "post-install/enable-service/{{ ansible_service_mgr }}.yaml"
- import_tasks: "post-install/bootstrap-cell.yaml"
