---
### === Zabbix agent defaults ===

### User and Group to run Zabbix agent under.
service_user: '{{ map_service_user[ansible_system] }}'
service_user_home: '{{ map_service_user_home[ansible_os_family] }}'
custom_service_user_home: '{{ map_default_home_folder[ansible_system] }}'
service_group: '{{ map_service_group[ansible_system] }}'

folder_log_setype: 'zabbix_log_t'
folder_log_seuser: 'system_u'
folder_pid_setype: 'zabbix_var_run_pid_t'

### Dictionary with service related settings
agent: '{{ map_agent_service_settings[ansible_system] }}'

### File to place systemd unit override settings.
agent_systemd_override_path: '{{ map_agent_systemd_override_path[agent_variant | string] }}'

### Location of logrotate settings.
agent_logrotate_path: '{{ map_agent_logrotate_path[agent_variant | string] }}'

### Option list for log rotation, using logrotate
logrotate_options:
  - weekly
  - maxsize 5M
  - rotate 12
  - compress
  - delaycompress
  - missingok
  - notifempty
  - create 0640 {{ service_user }} {{ service_group }}

### Default plugin list for Zabbix agent2
agent2_plugin_list: '{{ map_agent2_plugin_list[agent_major_version | string] }}'

### Used to calculate difference and clear plugin configuration of previous installation
full_agent2_plugin_list:
  - ceph
  - docker
  - memcached
  - modbus
  - mongodb
  - mqtt
  - mysql
  - oracle
  - postgresql
  - redis
  - smart
