---
- name: Unsupported OS
  fail:
    msg:
      - "Task files not found for this operating system:"
      - "{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}"
      - "{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | replace(' ', '_') }}"
      - "{{ ansible_os_family | replace(' ', '_') }}"
      - "{{ ansible_system | replace(' ', '_') }}"
