---
- name: Gather service facts
  service_facts:

- name: Permit kerberos traffic
  become: yes
  ansible.posix.firewalld:
    port: "{{ item }}"
    immediate: "{{ (ansible_facts.services['firewalld.service'].state == 'running') | ternary('yes', 'no') }}"
    permanent: yes
    state: enabled
  with_items:
    - 88/udp
    - 88/tcp
    - 749/udp
    - 749/tcp
  when: "'firewalld.service' in ansible_facts.services"
