---
#When running this playbook enable ask_pass and become_ask_pass in ansible.cfg file
- name: generate SSH key
  hosts: prod
  become: true
  tasks:
    - name: Changing PermitRootLogin value
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: restart sshd

    - name: Disable Password access
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: restart sshd
    - name: Enable Key access
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
      notify: restart sshd
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
