---
# you can use the failed_when keyword on a task to specify
# which condition indicate that the task has failed
# This is often use with command module
# execute a command where command output indicatea failure


- name: Testing failed_when feature
  hosts: test
  tasks:
  - ansible.builtin.shell: /usr/local/bin/create_users.sh
    register: command_result
    failed_when: "'Password missing' in command_result.stdout"


  # ansible.builtin.fail module can also be used to force a task failure.
  # You could instead write that example as two tasks
  #
  - name: Run user creation script
    ansible.builtin.shell: /usr/local/bin/create_users.sh
    register: command_result
    ignore_errors: yes

  - name: Report script failure
    asnible.builtin.fail:
      msg: "The password is missing in the output"
    when: "'password missing' in command_result.stdout"



# Changed_when

  - name: Validate httpd configuration
    ansible.builtin.shell: httpd -t
    changed_when: false
    register: httpd_config_status

  - ansible.builtin.shell:
      cmd: /usr/local/bin/upgrade-database
    register: command_result
    changed_when: "'Success' in command_result.stdout" #only change statue to CHANGED if condition fulfil
    notify:
      - restart_database

  handlers:
    - name: restart_database
      ansible.builtin.service:
        name: mariadb
        state: restarted
