---
- name: "OracleLinux-9: Add EPEL repository"
  become: yes
  yum:
    state: present
    name: epel-release
    update_cache: yes
  tags: root

- name: "OracleLinux-9: Install development packages (with enabled CRB 'Code Ready Builder' repo)"
  become: yes
  yum:
    state: present
    enablerepo: ol9_codeready_builder
    name:
      - autoconf
      - automake
      - bison
      - elfutils-devel
      - flex
      - fuse-devel
      - gcc
      - git
      - glibc-devel
      - jansson-devel
      - krb5-devel
      - libevent-devel
      - libtool
      - make
      - ncurses-devel
      - openssl-devel
      - pam-devel
      - perl-devel
      - perl-ExtUtils-Embed
      - redhat-rpm-config
      - rpm-build
      - swig
      - wget
  tags: root
