---
- name: Print free space on / filesystem
  hosts: client1
  gather_facts: true
  tasks:
    - name: Display free space
      ansible.builtin.debug:
        msg: >
          The root file system on {{ ansible_facts['fqdn'] }} has
          {{ item['block_available'] * item['block_size']/1000000 }}
          megabytes free.
      loop: "{{ ansible_facts['mounts'] }}"
      when: item['mount'] == '/'
