---
- name: Install OpenAFS server
  become: yes
  block:
    - name: Prevent services from starting during install
      copy:
        content: "exit 101"
        dest: "/usr/sbin/policy-rc.d"
        mode: "0755"
        backup: yes
      changed_when: false

    - name: Install OpenAFS server packages
      apt:
        state: present
        install_recommends: no
        update_cache: yes
        name:
          - openafs-fileserver
          - openafs-dbserver
          - openafs-krb5
      notify:
        - "server configuration changed"

    - name: Remove custom policy-rc file
      file:
        path: "/usr/sbin/policy-rc.d"
        state: absent
      changed_when: false

- name: Get installation paths
  openafs_contrib.openafs.openafs_get_install_paths:
  register: install_results

- name: Store installation facts
  become: yes
  openafs_contrib.openafs.openafs_store_facts:
    facts:
      install_method: "{{ afs_install_method }}"
      server_installed: yes
      server_service_name: openafs-fileserver
      bins: "{{ install_results.bins }}"
      dirs: "{{ install_results.dirs }}"
  when: not ansible_check_mode

- name: Set bosserver startup options
  become: yes
  copy:
    content: |
        DAEMON_ARGS="{{ afs_bosserver_opts }}"
    dest: "/etc/default/{{ ansible_local.openafs.server_service_name }}"
    mode: 0644
    owner: root
    group: "{{ afs_root_group }}"
  notify:
    - "server configuration changed"
