---
- name: Add OpenAFS yum repo
  become: yes
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ repo }}"
    gpgcheck: no
  loop:
    - "{{ afs_yum_repo }}"
  loop_control:
    loop_var: repo

- name: Install OpenAFS server packages
  become: yes
  yum:
    state: present
    name:
      - openafs-server
      - openafs-krb5

- name: Get installation paths
  openafs_contrib.openafs.openafs_get_install_paths:
  register: install_results

- name: Store installation facts
  become: yes
  openafs_contrib.openafs.openafs_store_facts:
    state: update
    facts:
      install_method: "{{ afs_install_method }}"
      server_installed: yes
      server_service_name: openafs-server
      bins: "{{ install_results.bins }}"
      dirs: "{{ install_results.dirs }}"
  when: not ansible_check_mode

- name: Set bosserver startup options
  become: yes
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: '^BOSSERVER_ARGS='
    line: 'BOSSERVER_ARGS="{{ afs_bosserver_opts }}"'
    state: present
  notify:
    - "server configuration changed"
