---
map_os_transition:
  RedHat:
    '6': '6'
    '7': '7'
    '8': '8'
    '9': '9'
  OracleLinux:
    '6': '6'
    '7': '7'
    '8': '8'
    '9': '9'
  CentOS:
    '6': '6'
    '7': '7'
    '8': '8'
    '9': '9'
  Rocky:
    '8': '8'
    '9': '9'
  AlmaLinux:
    '8': '8'
    '9': '9'
  Amazon:
    '2': '7'
    '2023': '9'
  Fedora:
    '19': '7'
    '20': '7'
    '21': '7'
    '22': '7'
    '23': '7'
    '24': '7'
    '25': '7'
    '26': '7'
    '27': '7'
    '28': '8'
    '29': '8'
    '30': '8'
    '31': '8'
    '32': '8'
    '33': '8'
    '34': '9'
    '35': '9'
    '36': '9'
    '37': '9'
    '38': '9'
    '39': '9'

map_gpg_key:
  '7': 'http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591'
  '8': 'http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591'
  '9': 'http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD'
