#------------------------------------------------------------------------------
# Ensure a kernel-headers package is installed that matches the current kernel
# version. This is required in order to build the OpenAFS client kernel module.
#

# Be sure we have the tools needed to build the kernel module when we are not
# installing the full suite of development packages.
- name: "Debian: Install kernel module build tools."
  become: yes
  apt:
    state: present
    update_cache: true
    name:
      - autoconf
      - automake
      - gcc
      - libtool
      - make

- name: "Query linux-header package."
  command:
    cmd: "dpkg-query --show --showformat='${Status}:${Package}\n' linux-headers-{{ ansible_kernel }}"
  changed_when: False
  failed_when: False
  register: dpkg_query

- debug:
    var: dpkg_query
    verbosity: 1

- debug:
    msg: "linux-headers package is already installed for {{ ansible_kernel }}."
  when: ansible_kernel not in dpkg_query.stdout_lines

- name: "Install kernel headers."
  when: ansible_kernel not in dpkg_query.stdout_lines
  become: yes
  block:
    - name: "Install linux-headers"
      apt:
        state: present
        name: "linux-headers-{{ ansible_kernel }}"

  rescue:
    # If we are unable to install the linux-headers package, the current
    # kernel version may be too old. When allowed, automatically update
    # the kernel then retry the linux-headers install. This entails a reboot.
    - fail:
        msg: Kernel update and reboot required.
      when: not (afs_devel_allow_kernel_update | d('no') | bool)

    - name: Update kernel with apt
      apt:
        state: latest
        name:
          - 'linux-image*'
        only_upgrade: yes
        update_cache: yes
      register: apt_update_results

    - name: Reboot
      when: apt_update_results.changed
      block:
        - set_fact:
            old_kernel_version: "{{ ansible_kernel }}"

        - name: Rebooting
          reboot:
            reboot_timeout: 600

        - name: Waiting for reboot to complete
          wait_for_connection:

        - name: Gathering facts
          setup:

        - debug:
            msg: "Updated kernel from {{ old_kernel_version }} to {{ ansible_kernel }}."

        - name: "Install linux-headers"
          apt:
            state: present
            name: "linux-headers-{{ ansible_kernel }}"
