---
#
# Ensure the kernel-devel package is installed which matches the currently
# running kernel version.
#

# Be sure we have the tools needed to build the kernel module when we are not
# installing the full suite of development packages.
- name: "RedHat: Install kernel module build tools."
  become: yes
  yum:
    state: present
    name:
      - autoconf
      - automake
      - gcc
      - libtool
      - make

- name: "RedHat: Query kernel-devel packages."
  command:
    cmd: "rpm -q --qf='%{VERSION}-%{RELEASE}.%{ARCH}\n' kernel-devel"
  changed_when: False
  failed_when: False
  register: rpm_query

- name: "RedHat: Show query results."
  debug:
    msg: "kernel-devel package is already installed for {{ ansible_kernel }}."
  when: ansible_kernel in rpm_query.stdout_lines

- name: "RedHat: Install kernel headers."
  when: ansible_kernel not in rpm_query.stdout_lines
  become: yes
  block:
    - name: "RedHat: Install kernel-devel package."
      yum:
        state: present
        name: "kernel-devel-uname-r == {{ ansible_kernel }}"
  rescue:
    # If we are unable to install the kernel-devel package the current
    # kernel version may be too old. When allowed, automatically update
    # the kernel and then retry the kernel-devel install.
    # This entails a reboot.
    - fail:
        msg: Kernel update and reboot required.
      when: not (afs_devel_allow_kernel_update | d('no') | bool)

    - name: "RedHat: Update kernel."
      yum:
        state: latest
        name:
          - kernel
      register: yum_update_results

    - name: "RedHat: Reboot."
      when: yum_update_results.changed
      block:
        - set_fact:
            old_kernel_version: "{{ ansible_kernel }}"

        - name: "RedHat: Rebooting."
          reboot:
            reboot_timeout: 600

        - name: "RedHat: Waiting for reboot to complete."
          wait_for_connection:

        - name: "RedHat: Gathering facts."
          setup:

        - name: "RedHat: Show kernel versions."
          debug:
            msg: "Updated kernel from {{ old_kernel_version }} to {{ ansible_kernel }}."

        - name: "RedHat: Install kernel-devel package."
          yum:
            state: present
            name: "kernel-devel-uname-r == {{ ansible_kernel }}"
