---
#- debug: var=ansible_distribution
#- debug: var=ansible_distribution_version
#- debug: var=ansible_distribution_major_version
#- debug: var=ansible_os_family
#- debug: var=ansible_system

- name: Gather variables for each operating system
  include_vars: "{{ afs_common_os_item }}"
  loop_control:
    loop_var: afs_common_os_item
  with_first_found:
    - "{{ role_path }}/vars/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_distribution | replace(' ', '_') }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_os_family }}.yaml"
    - "{{ role_path }}/vars/{{ ansible_system }}.yaml"
    - "{{ role_path }}/vars/defaults.yaml"

- set_fact:
    afs_install_method: "{{ _afs_install_method | d('managed') }}"
  when: afs_install_method is undefined or afs_install_method | count == 0

- debug:
    var: afs_install_method
