---
# Kerberos realm name
afs_realm: EXAMPLE.COM

# Path to locally generated files.
afs_realm_files: "{{ '~/.ansible-openafs' | expanduser }}/realm/{{ afs_realm }}"

# KDC max ticket life.
afs_krb_max_life: 10h 0m 0s

# KDC max renewable life.
afs_krb_max_renewable_life: 7d 0h 0m 0s

# KDC supported enctypes.
afs_krb_supported_enctypes:
  - aes256-cts-hmac-sha1-96:normal
  - aes128-cts-hmac-sha1-96:normal

# KDC default principal flags.
afs_krb_default_principal_flags: +preauth

# Kerberos database master password (random default).
# NOTE: Put this in ansible-vault!
afs_krb_master_password: "{{ lookup('password', afs_realm_files + '/afs_krb_master_password chars=ascii_letters,digits,hexdigits length=32') }}"

# Kerberos admin principal
afs_krb_admin_principal: "root/admin"
