---
- name: "Restart OpenAFS server service."
  become: yes
  service:
    name: "{{ ansible_local.openafs.server_service_name }}"
    state: restarted
  listen: "server configuration changed"
  when: not (afs_cancel_restart_server_service | d('no') | bool)
