---
- name: Prepare User Authentication
  hosts: client1
  gather_facts: true
  tasks:

    - name: Create devops_user if missing, make sure is member of correct groups
      ansible.builtin.user:
        name: devops_user
        shell: /bin/bash
        groups: sys_admin, developers
        append: true

    - name: Create an SSH key for user1
      ansible.builtin.user:
        name: user1
        generate_ssh_key: true
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_my_rsa

    - name: Verify that the auditors group exists
      ansible.builtin.group:
        name: auditors
        state: present

    - name: Copy host keys to remote servers
      ansible.builtin.known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: servera.lab.example.com
        key: servera.lab.example.com,172.0.0.2 ssh-rsa ASDKFJKL34jkFk44j

       #key: "{{ lookup('ansible.builtin.file', 'pubkeys/serverb') }}"

    - name: Set authorized key
      ansible.posix.authorized_key:
        user: user1
        state: present
        key: "{{ lookup('ansible.builtin.file', 'files/user1/id_rsa.pub') }}"
    
    - name: Modify sudo to allow the group01 group sudo without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/group1
        state: present
        create: true
        mode: 0440
        line: "%group01 ALL=(ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s
