download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-crypto-2.17.0.tar.gz
format_version: 1.0.0
name: crypto
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.17.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/crypto/versions/2.17.0/
