---
- name: change
  hosts: all
  become: yes
  tasks:
    - name: change entry
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: restart service
      service:
        name: sshd
        state: restarted
