---
- name: lvm
  hosts: dev
  gather_facts: true
  become: yes
  tasks:
    - name: Create lv
      block:
        - name: first check if research vg exists or not
          debug:
            #var: ansible_facts['lvm']['vgs']
            msg: "research vg not found"
          when: "'research' not in ansible_facts['lvm']['vgs']"
        - name: Create vg
          shell: vgcreate research /dev/sda
          when: "'research' not in ansible_facts['lvm']['vgs']"
