---
#
# Update the server configuration files:
#
#   - ThisCell
#   - CellServDB
#   - BosConfig (via BosConfig.new)
#   - krb.conf (if the realm name is different than the cell name)
#   - NetInfo
#   - NetRestrict
#
# We cannot change the BosConfig directly since the bosserver may be
# running, so create a shadow config file called BosConfig.ansible and
# if that file is changed, create a BosConfig.new and notify a handler
# to restart the bosserver to pivot the BosConfig.new to BosConfig
# and load the new configuration.
#

- name: Check for cold start
  when: afs_server_cold_start is undefined or afs_server_cold_start == 'detect'
  block:
    - name: Check for cold start
      become: yes
      stat:
        path: "{{ afs_afsbosconfigdir }}/BosConfig"
      register: bosconfig_stat
    - set_fact:
        afs_server_cold_start: "{{ not bosconfig_stat.stat.exists }}"

- debug:
    var: afs_server_cold_start

- name: Ensure server configuration directory exists
  become: yes
  file:
    state: directory
    path: "{{ afs_afsconfdir }}"
    mode: "755"
    owner: root
    group: "{{ afs_root_group }}"

- name: Ensure server local directory exists
  become: yes
  file:
    state: directory
    path: "{{ afs_afslocaldir }}"
    mode: "700"
    owner: root
    group: "{{ afs_root_group }}"

- name: Ensure BosConfig directory exists
  become: yes
  file:
    state: directory
    path: "{{ afs_afsbosconfigdir }}"
    mode: "755"
    owner: root
    group: "{{ afs_root_group }}"
  # The BosConfig dir has the same name and mode as afslocaldir when using
  # Transarc-style paths, otherwise it should have mode 755.
  when: afs_afsbosconfigdir != afs_afslocaldir

- name: Create configuration files
  become: yes
  template:
    src: "{{ role_path }}/templates/{{ item.name }}.j2"
    dest: "{{ item.path }}/{{ item.name }}"
    owner: root
    group: "{{ afs_root_group }}"
    mode: "644"
  loop:
    - name: ThisCell
      path: "{{ afs_afsconfdir }}"
    - name: CellServDB
      path: "{{ afs_afsconfdir }}"
    - name: BosConfig.ansible
      path: "{{ afs_afsbosconfigdir }}"
  register: config_files

- name: Create BosConfig.new file
  become: yes
  copy:
    src: "{{ afs_afsbosconfigdir }}/BosConfig.ansible"
    dest: "{{ afs_afsbosconfigdir }}/BosConfig.new"
    remote_src: yes
  when:
    - not ansible_check_mode
    - (config_files.results | selectattr('dest', 'search', 'BosConfig') | list)[0].changed
  notify:
    - "server configuration changed"

- name: Ensure admin is a superuser
  become: yes
  lineinfile:
    state: present
    create: yes
    line: "{{ item }}"
    path: "{{ afs_afsconfdir }}/UserList"
  with_items: "{{ ((afs_admin | type_debug) == 'list') | ternary(afs_admin, [afs_admin]) }}"

- name: Create krb.conf
  become: yes
  copy:
    content: "{{ afs_realm }}"
    dest: "{{ afs_afsconfdir }}/krb.conf"
    mode: "644"
    owner: root
    group: "{{ afs_root_group }}"
  when: afs_realm != afs_cell.upper()

- name: Remove NetInfo
  become: yes
  file:
    state: absent
    path: "{{ afs_afslocaldir }}/NetInfo"
  when:
    - (afs_server_netinfo is undefined) or (afs_server_netinfo | count == 0)
  notify:
    - "server configuration changed"

- name: Update NetInfo
  become: yes
  template:
    src: "{{ role_path }}/templates/NetInfo.j2"
    dest: "{{ afs_afslocaldir }}/NetInfo"
    owner: root
    group: "{{ afs_root_group }}"
    mode: "644"
  when:
    - afs_server_netinfo is defined
    - afs_server_netinfo | count > 0
  notify:
    - "server configuration changed"

- name: Remove NetRestrict
  become: yes
  file:
    state: absent
    path: "{{ afs_afslocaldir }}/NetRestrict"
  when:
    - (afs_server_netrestrict is undefined) or (afs_server_netrestrict | count == 0)
  notify:
    - "server configuration changed"

- name: Update NetRestrict
  become: yes
  template:
    src: "{{ role_path }}/templates/NetRestrict.j2"
    dest: "{{ afs_afslocaldir }}/NetRestrict"
    owner: root
    group: "{{ afs_root_group }}"
    mode: "644"
  when:
    - afs_server_netrestrict is defined
    - afs_server_netrestrict | count > 0
  notify:
    - "server configuration changed"
