---
- name: Upload service keytab
  become: yes
  copy:
    src: "{{ afs_service_keytab }}"
    dest: "{{ afs_afsconfdir }}/rxkad.keytab"
    mode: 0600
    owner: root
    group: "{{ afs_root_group }}"
  when:
    - not afs_service_keytab_externally_managed | bool

- name: Add service keys
  become: yes
  openafs_contrib.openafs.openafs_keys:
    state: present
    keytab: "{{ afs_afsconfdir }}/rxkad.keytab"
    cell: "{{ afs_cell }}"
    realm: "{{ afs_realm }}"
