---
#
# Install the OpenAFS kernel module with DKMS. This install method
# requires a private yum repo populated with OpenAFS rpm packages.
#

- name: Add OpenAFS yum repo
  become: yes
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ repo }}"
    gpgcheck: no
  loop:
    - "{{ afs_yum_repo }}"
  loop_control:
    loop_var: "repo"

# Workaround missing dkms-openafs package requires. These
# must be installed with a separate yum command before the
# openafs rpms are installed.
- name: Install kernel module build requirements
  import_role:
    name: openafs_contrib.openafs.openafs_devel_kernel

- name: Install OpenAFS client with DKMS
  become: yes
  yum:
    state: present
    name:
      - openafs
      - openafs-client
      - dkms-openafs
      - openafs-krb5

- name: Get dkms status
  command: /usr/sbin/dkms status
  check_mode: no
  changed_when: false
  register: dkms_status

- debug:
    var: dkms_status
    verbosity: 1

- name: Verify openafs dkms status is installed
  assert:
    that:
      dkms_status.stdout is regex('^openafs/.*: installed')

- name: Get installation paths
  openafs_contrib.openafs.openafs_get_install_paths:
  register: install_results

- name: Store installation facts
  become: yes
  openafs_contrib.openafs.openafs_store_facts:
    state: update
    facts:
      install_method: "{{ afs_install_method }}"
      client_installed: yes
      client_service_name: openafs-client
      bins: "{{ install_results.bins }}"
      dirs: "{{ install_results.dirs }}"
      cacheinfo: "{{ install_results.cacheinfo }}"
  when: not ansible_check_mode

- name: Set client startup options
  become: yes
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: "^AFSD_ARGS="
    line: 'AFSD_ARGS="{{ afs_afsd_opts }}"'
    state: present
  when: afs_afsd_opts is defined
  notify:
    - "client configuration changed"
