---
- name: "Debian: Install kernel module build requirements."
  import_role:
    name: openafs_contrib.openafs.openafs_devel_kernel

- name: "Debian: Install client"
  become: yes
  block:
    - name: "Debian: Prevent services from starting during install"
      copy:
        content: "exit 101"
        dest: "/usr/sbin/policy-rc.d"
        mode: "0755"
      changed_when: false

    - name: "Debian: Install OpenAFS client packages"
      apt:
        state: present
        install_recommends: no
        name:
          - openafs-client
          - openafs-krb5
          - openafs-modules-dkms

    - name: "Debian: Restore installation policy"
      file:
        path: "/usr/sbin/policy-rc.d"
        state: absent
      changed_when: false

- name: Get installation paths
  openafs_contrib.openafs.openafs_get_install_paths:
  register: install_results

- name: Store installation facts
  become: yes
  openafs_contrib.openafs.openafs_store_facts:
    state: update
    facts:
      install_method: "{{ afs_install_method }}"
      client_installed: yes
      client_service_name: openafs-client
      bins: "{{ install_results.bins }}"
      dirs: "{{ install_results.dirs }}"
      cacheinfo: "{{ install_results.cacheinfo }}"
  when: not ansible_check_mode
