---
- name: "Unsupported install method."
  fail:
    msg:
      - "Install method {{ afs_install_method }} is not supported."
      - "File not found:"
      - "{{ afs_install_method }}-{{ ansible_distribution | replace(' ', '_') | lower }}-{{ afs_module_install_method }}.yaml"
      - "{{ afs_install_method }}-{{ ansible_distribution | replace(' ', '_') | lower }}.yaml"
      - "{{ afs_install_method }}-{{ ansible_os_family | lower }}-{{ afs_module_install_method }}.yaml"
      - "{{ afs_install_method }}-{{ ansible_os_family | lower }}.yaml"
      - "{{ afs_install_method }}.yaml"
      - "Search path:"
      - "{{ role_path }}/tasks/install"
